export const SITE_NAME = 'AULM Precious Metal Trader'
export const CONTACT_EMAIL = 'contact@aulmtrading.com'
export const COMPLIANCE_EMAIL = 'contact@aulmtrading.com'
export const LICENSE_NUMBER = '85927'
export const GOAML_REGISTRATION_CODE = 'GMLMOEC41724064013'
export const GOAML_PORTAL_URL = 'https://services.uaefiu.gov.ae/goaml/'
export const GOAML_FIU_URL = 'https://services.uaefiu.gov.ae/'
