import type { CrmApproval, CrmClient, CrmEscrow, CrmEvaultPosition } from './types'

export const CRM_CLIENTS: CrmClient[] = [
  {
    id: 'client-001',
    reference: 'AULM-C-0001',
    legalName: 'Atlas Mining & Commodities Ltd',
    tradingName: 'Atlas Commodities',
    kind: 'supplier',
    status: 'active',
    kycStatus: 'approved',
    riskRating: 'low',
    country: 'Ghana',
    registrationNumber: 'GH-CS-884021',
    email: 'operations@atlascommodities.com',
    phone: '+233 30 221 4400',
    assignedTo: 'Lorenzo Meyer',
    sourceOfFunds: 'Mining operations and commodity exports',
    expectedAnnualVolume: 28_500_000,
    annualRevenue: 41_200_000,
    currency: 'USD',
    tags: ['Gold supplier', 'Priority', 'West Africa'],
    notes: 'Primary doré supplier. Requires assay confirmation before each release.',
    createdAt: '2025-10-14T09:00:00Z',
    contacts: [
      {
        id: 'contact-001',
        fullName: 'Kwame Mensah',
        title: 'Managing Director',
        email: 'kwame@atlascommodities.com',
        phone: '+233 24 555 0192',
        role: 'UBO · Signatory',
        nationality: 'Ghanaian',
        ownershipPercent: 62,
        isPrimary: true,
        isAuthorisedSignatory: true,
      },
      {
        id: 'contact-002',
        fullName: 'Ama Boateng',
        title: 'Head of Export Operations',
        email: 'ama@atlascommodities.com',
        phone: '+233 24 555 0118',
        role: 'Operations',
        nationality: 'Ghanaian',
      },
    ],
    holdings: [
      {
        id: 'holding-001',
        commodityCode: 'XAU',
        commodityName: 'Gold',
        quantity: 184.5,
        unit: 'kg',
        purity: 0.916,
        positionType: 'verified',
        location: 'Accra secure facility',
        valuationUsd: 14_820_000,
        asOf: '2026-07-17',
      },
      {
        id: 'holding-002',
        commodityCode: 'XAG',
        commodityName: 'Silver',
        quantity: 920,
        unit: 'kg',
        purity: 0.998,
        positionType: 'declared',
        location: 'Tema warehouse',
        valuationUsd: 1_048_000,
        asOf: '2026-07-15',
      },
    ],
    transactions: [
      {
        id: 'txn-001',
        reference: 'AULM-T-2026-0042',
        type: 'purchase',
        status: 'in_progress',
        commodityCode: 'XAU',
        quantity: 42.5,
        unit: 'kg',
        value: 3_410_000,
        currency: 'USD',
        date: '2026-07-12',
      },
      {
        id: 'txn-002',
        reference: 'AULM-T-2026-0027',
        type: 'purchase',
        status: 'completed',
        commodityCode: 'XAU',
        quantity: 31.2,
        unit: 'kg',
        value: 2_485_000,
        currency: 'USD',
        date: '2026-05-03',
      },
    ],
    documents: [
      {
        id: 'doc-001',
        title: 'Certificate of Incorporation',
        type: 'KYB',
        status: 'approved',
        version: 2,
        uploadedBy: 'Sarah König',
        uploadedAt: '2026-06-12T11:20:00Z',
        expiresAt: '2027-06-12',
      },
      {
        id: 'doc-002',
        title: 'SPA · Gold Lot 2026-0042',
        type: 'SPA',
        status: 'signed',
        version: 3,
        uploadedBy: 'Lorenzo Meyer',
        uploadedAt: '2026-07-10T14:44:00Z',
      },
      {
        id: 'doc-003',
        title: 'Air Waybill · ACC-DXB',
        type: 'AWB',
        status: 'under_review',
        version: 1,
        uploadedBy: 'Daniel Weber',
        uploadedAt: '2026-07-18T08:15:00Z',
      },
    ],
    activity: [
      {
        id: 'activity-001',
        actor: 'Daniel Weber',
        action: 'uploaded Air Waybill · ACC-DXB',
        timestamp: '2026-07-18T08:15:00Z',
      },
      {
        id: 'activity-002',
        actor: 'Sarah König',
        action: 'approved Certificate of Incorporation',
        timestamp: '2026-07-17T14:30:00Z',
      },
      {
        id: 'activity-003',
        actor: 'Lorenzo Meyer',
        action: 'updated annual transaction volume',
        timestamp: '2026-07-16T10:05:00Z',
      },
    ],
  },
  {
    id: 'client-002',
    reference: 'AULM-C-0002',
    legalName: 'Helvetic Refining AG',
    kind: 'buyer',
    status: 'active',
    kycStatus: 'approved',
    riskRating: 'low',
    country: 'Switzerland',
    registrationNumber: 'CHE-441.823.019',
    email: 'trade@helvetic-refining.ch',
    phone: '+41 44 555 91 00',
    assignedTo: 'Sophie Laurent',
    sourceOfFunds: 'Refining and institutional bullion sales',
    expectedAnnualVolume: 64_000_000,
    annualRevenue: 118_000_000,
    currency: 'CHF',
    tags: ['Gold buyer', 'Refinery', 'Europe'],
    notes: 'Fast settlement buyer. Approved for deferred assay settlement.',
    createdAt: '2025-11-03T09:00:00Z',
    contacts: [],
    holdings: [
      {
        id: 'holding-003',
        commodityCode: 'XAU',
        commodityName: 'Gold',
        quantity: 410,
        unit: 'kg',
        purity: 0.9999,
        positionType: 'verified',
        location: 'Zurich',
        valuationUsd: 32_910_000,
        asOf: '2026-07-18',
      },
    ],
    transactions: [
      {
        id: 'txn-003',
        reference: 'AULM-T-2026-0038',
        type: 'sale',
        status: 'completed',
        commodityCode: 'XAU',
        quantity: 58,
        unit: 'kg',
        value: 4_612_000,
        currency: 'USD',
        date: '2026-06-21',
      },
    ],
    documents: [],
    activity: [],
  },
  {
    id: 'client-003',
    reference: 'AULM-C-0003',
    legalName: 'Emirates Industrial Metals FZE',
    kind: 'both',
    status: 'onboarding',
    kycStatus: 'under_review',
    riskRating: 'medium',
    country: 'United Arab Emirates',
    registrationNumber: 'IFZA-99218',
    email: 'finance@eim-fze.ae',
    phone: '+971 4 555 2208',
    assignedTo: 'Sarah König',
    sourceOfFunds: 'Industrial metals trading',
    expectedAnnualVolume: 19_500_000,
    annualRevenue: 29_800_000,
    currency: 'AED',
    tags: ['Copper', 'UAE', 'Onboarding'],
    notes: 'Awaiting UBO source-of-wealth confirmation.',
    createdAt: '2026-06-28T09:00:00Z',
    contacts: [],
    holdings: [
      {
        id: 'holding-004',
        commodityCode: 'CU',
        commodityName: 'Copper',
        quantity: 860,
        unit: 'mt',
        positionType: 'declared',
        location: 'Jebel Ali',
        valuationUsd: 8_290_000,
        asOf: '2026-07-01',
      },
    ],
    transactions: [],
    documents: [
      {
        id: 'doc-004',
        title: 'Trade License',
        type: 'KYB',
        status: 'under_review',
        version: 1,
        uploadedBy: 'Client portal',
        uploadedAt: '2026-07-14T12:15:00Z',
      },
    ],
    activity: [],
  },
  {
    id: 'client-004',
    reference: 'AULM-C-0004',
    legalName: 'North Sea Energy Trading BV',
    kind: 'buyer',
    status: 'lead',
    kycStatus: 'invited',
    riskRating: 'unrated',
    country: 'Netherlands',
    registrationNumber: 'NL-KVK-8841291',
    email: 'legal@nset.nl',
    phone: '+31 20 555 0190',
    assignedTo: 'Lorenzo Meyer',
    sourceOfFunds: '',
    expectedAnnualVolume: 52_000_000,
    annualRevenue: 0,
    currency: 'EUR',
    tags: ['Oil', 'Gas', 'Lead'],
    notes: 'Digital onboarding invite sent 18 July.',
    createdAt: '2026-07-18T09:00:00Z',
    contacts: [],
    holdings: [],
    transactions: [],
    documents: [],
    activity: [],
  },
]

export const CRM_STAFF = [
  { id: 'staff-001', name: 'Lorenzo Meyer', role: 'Superadmin', department: 'Management' },
  { id: 'staff-002', name: 'Sarah König', role: 'Compliance', department: 'Compliance' },
  { id: 'staff-003', name: 'Daniel Weber', role: 'Operations', department: 'Trade Operations' },
  { id: 'staff-004', name: 'Sophie Laurent', role: 'Finance', department: 'Treasury' },
]

export const CRM_ESCROWS: CrmEscrow[] = [
  {
    id: 'esc-001',
    reference: 'ESC-2026-0142',
    clientId: 'client-001',
    clientName: 'Atlas Commodities',
    commodity: 'Gold · 42.5 kg',
    amountUsd: 3_410_000,
    status: 'in_transit',
    clearingAgent: 'Dubai Clearing Desk',
    openedAt: '2026-07-08',
    updatedAt: '2026-07-18',
  },
  {
    id: 'esc-002',
    reference: 'ESC-2026-0138',
    clientId: 'client-002',
    clientName: 'Helvetic Refining AG',
    commodity: 'Gold · 58 kg',
    amountUsd: 1_850_000,
    status: 'buyer_review',
    clearingAgent: 'Zurich Metals Clear',
    openedAt: '2026-06-19',
    updatedAt: '2026-07-19',
  },
  {
    id: 'esc-003',
    reference: 'ESC-2026-0129',
    clientId: 'client-003',
    clientName: 'Emirates Industrial Metals FZE',
    commodity: 'Copper · 120 mt',
    amountUsd: 980_000,
    status: 'certificate_pending',
    clearingAgent: 'Jebel Ali Clear',
    openedAt: '2026-07-02',
    updatedAt: '2026-07-17',
  },
  {
    id: 'esc-004',
    reference: 'ESC-2026-0111',
    clientId: 'client-001',
    clientName: 'Atlas Commodities',
    commodity: 'Silver · 400 kg',
    amountUsd: 412_000,
    status: 'funded',
    clearingAgent: 'Dubai Clearing Desk',
    openedAt: '2026-07-15',
    updatedAt: '2026-07-16',
  },
]

export const CRM_EVAULT: CrmEvaultPosition[] = [
  {
    id: 'ev-001',
    clientId: 'client-002',
    clientName: 'Helvetic Refining AG',
    product: 'flexible',
    principalUsd: 1_200_000,
    apy: 3.4,
    accruedUsd: 18_420,
    openedAt: '2026-01-12',
    status: 'active',
  },
  {
    id: 'ev-002',
    clientId: 'client-001',
    clientName: 'Atlas Commodities',
    product: 'locked_12m',
    principalUsd: 2_500_000,
    apy: 5.5,
    accruedUsd: 76_800,
    openedAt: '2026-02-01',
    maturesAt: '2027-02-01',
    status: 'active',
  },
  {
    id: 'ev-003',
    clientId: 'client-003',
    clientName: 'Emirates Industrial Metals FZE',
    product: 'locked_6m',
    principalUsd: 750_000,
    apy: 5.5,
    accruedUsd: 12_110,
    openedAt: '2026-04-20',
    maturesAt: '2026-10-20',
    status: 'maturing',
  },
]

export const CRM_APPROVALS: CrmApproval[] = [
  {
    id: 'apr-001',
    kind: 'escrow_release',
    title: 'Release escrow ESC-2026-0138',
    clientName: 'Helvetic Refining AG',
    amountUsd: 1_850_000,
    requestedBy: 'Daniel Weber',
    requestedAt: '2026-07-19T09:40:00Z',
    priority: 'high',
    status: 'pending',
  },
  {
    id: 'apr-002',
    kind: 'kyc',
    title: 'Approve KYC · Emirates Industrial Metals',
    clientName: 'Emirates Industrial Metals FZE',
    requestedBy: 'Sarah König',
    requestedAt: '2026-07-18T16:12:00Z',
    priority: 'high',
    status: 'pending',
  },
  {
    id: 'apr-003',
    kind: 'payment',
    title: 'Outbound payment · Swiss Refinery AG',
    clientName: 'Atlas Commodities',
    amountUsd: 125_000,
    requestedBy: 'Sophie Laurent',
    requestedAt: '2026-07-18T11:05:00Z',
    priority: 'normal',
    status: 'pending',
  },
  {
    id: 'apr-004',
    kind: 'evault_withdrawal',
    title: 'E-Vault withdrawal · flexible',
    clientName: 'Helvetic Refining AG',
    amountUsd: 250_000,
    requestedBy: 'Client portal',
    requestedAt: '2026-07-17T14:22:00Z',
    priority: 'normal',
    status: 'pending',
  },
  {
    id: 'apr-005',
    kind: 'document',
    title: 'AWB review · ACC-DXB',
    clientName: 'Atlas Commodities',
    requestedBy: 'Daniel Weber',
    requestedAt: '2026-07-18T08:20:00Z',
    priority: 'low',
    status: 'pending',
  },
]
